### ISSUE TITLE
http UI

### ISSUE THREAD

**Issue by dagbdagb** [janbar/noson-app#101]
Hi

QT has a module QtWasm to compile to a Webapp. No idea about feasability for noson in particular, or if this is the most efficient way to give Noson a web frontend. Worth looking into?

**Comment by janbar** [comment]
No way to use Wasm because it doesn't support thread. The app is based on a backend receiving upnp notifications and many threads are required to handle the media controllers.

**Comment by dagbdagb** [comment]
OK.
