### ISSUE TITLE
Add snap install instructions

### ISSUE THREAD

**Issue by popey** [janbar/noson-app#11]
Great to see you have a snap of noson-app in the store. I think more people will discover it, and get the benefits of automatic updates if you put it in your install instructions.  Perhaps on the http://janbar.github.io/noson-app/index.html  page you could have some text such as:-

"On [snap enabled](https://snapcraft.io/docs/core/install) systems, install noson-app with the following command:-
    snap install noson-app
"

**Comment by janbar** [comment]
Yes you're right

**Comment by janbar** [comment]
I added instructions in the project page http://janbar.github.io/noson-app/
