### ISSUE TITLE
Volume slider only react to clicks

### ISSUE THREAD

**Issue by bosim** [janbar/noson-app#116]
The volume slider only react to clicks not using the scroll wheel (i.e. two finger scroll on a laptop at least). The slider moves however it does not propagate. Only way to turn up the sound is to click on the slider. Seems pretty much like a regression.

**Comment by janbar** [comment]
Thanks to report this. I never use the wheel so ...

**Comment by janbar** [comment]
fixed by the commit 2783b05058e5718bdc1a0dacefcc486414e84694

**Comment by bosim** [comment]
Works like a charm! Thanks!
