### ISSUE TITLE
accounts configured through the the official app missing

### ISSUE THREAD

**Issue by davidwinterstein** [janbar/noson-app#118]
Hi, I just installed the app with `flatpak` and it recognized the several devices and rooms in our office correctly.

For some reason, the multiple Spotify accounts already configured through the Sonos Controller app for Windows are missing and I can't find them anywhere in the app.

Pairing my own account works, but I'd like to use the company's so it doesn't stop playback on my private devices when I'm not in the office and someone plays the music I queued.

**Comment by janbar** [comment]
You can create more than one account for spotify. Just add an other Spotify service, and login with the other account.
for now the app doesn't tag the services. But they stay in the same order as creation time.

**Comment by davidwinterstein** [comment]
> First the app cannot gatherer the registered accounts from your sonos devices. You have to add already registered services to browse the content from the services and to add asset in queue of the playback.

Ok, I didn't know that. Is this because it's simply not possible by design or is documentation from Sonos missing or something else? Will this be supported in the future?

**Comment by janbar** [comment]
Simply not possible. The user accounts and registered services are closed/obfuscated.
With the next release (4.3.1) I added a dialog to tag the added services. So by example you will able to add one Spotify with tag "office" and an other with tag "home". The first will work at office and the second will work at home, to enqueue asset.

**Comment by davidwinterstein** [comment]
> Simply not possible. The user accounts and registered services are closed/obfuscated.

That's a shame, but can't be helped, then. Thanks a lot for your effort!
