### ISSUE TITLE
Fails to start on Linux Mint 18.2

### ISSUE THREAD

**Issue by fischermatte** [janbar/noson-app#13]
I followed the instructions on the project page:

`sudo add-apt-repository ppa:jlbarriere68/noson-app`
`sudo apt-get update`
`sudo apt-get install noson-app`

But the noson-app window just pops up for a second and then closes again.

Note: Linux Mint 18.2 is based on Ubuntu 16.04

**Comment by janbar** [comment]
You could try to enable debug output as the following:

`noson-app --debug 2>&1 | tee noson.log`

The log will show us what happen.

**Comment by fischermatte** [comment]
Thx for quick response. Wanted to provide the debug log, but noson-app started today after reboot! so i am sorry, can not reproduce it anymore. really appreciate your work here!!
