### ISSUE TITLE
Action can't be performed trying to play Spotify playlist

### ISSUE THREAD

**Issue by YoungJules** [janbar/noson-app#131]
Am registered for Spotify Premium. Have registered service in Noson, signed in to Spotify and authorised Sonos. But cannot play any playlists from Spotify. 
Last lines of noson --debug:
(SONOS)GetResponse: HTTP/1.1 200 OK
(SONOS)GetResponse: CONTENT-TYPE: text/xml; charset="utf-8"
(SONOS)GetResponse: EXT: 
(SONOS)GetResponse: TRANSFER-ENCODING: chunked
(SONOS)GetResponse: Server: Linux UPnP/1.0 Sonos/56.0-76060 (ZPS3)
(SONOS)GetResponse: Connection: close
(SONOS)GetResponse: 
(SONOS)ReadChunk: chunked data (278)
(SONOS)ReadChunk: chunked data (0)
(SONOS)Request: Result = <DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"></DIDL-Lite>
(SONOS)Request: NumberReturned = 0
(SONOS)Request: TotalMatches = 0
(SONOS)Request: UpdateID = 5
(SONOS)BrowseContent: count 0
(SONOS)GetResponse: HTTP/1.1 500 Internal Server Error
(SONOS)GetResponse: CONTENT-LENGTH: 347
(SONOS)GetResponse: CONTENT-TYPE: text/xml; charset="utf-8"
(SONOS)GetResponse: EXT: 
(SONOS)GetResponse: Server: Linux UPnP/1.0 Sonos/56.0-76060 (ZPS3)
(SONOS)GetResponse: Connection: close
(SONOS)GetResponse: 
(SONOS)WSResponse: server error (500)
(SONOS)Request: invalid response

Thanks for looking :-)

**Comment by janbar** [comment]
Have you registered the Spotify service with the Official Sonos App before ?
It is required to register the service with the official app to enable the service on your sonos device(s). Noson can't do it and also it cannot retrieve the list of already enabled services in the device. So first stage you have to register the service with the sonos app (Android or Pc/Mac), then it should work. Let me know.

**Comment by YoungJules** [comment]
Many thanks for the reply. Indeed, I had to register the service outside of Noson, although Noson appears to go through all the steps of registration successfully.
Thank you!
