### ISSUE TITLE
noson view zoomed way in

### ISSUE THREAD

**Issue by shawnburke** [janbar/noson-app#132]
My Noson window view has gotten very zoomed in, I can't figure out how to reset it.

Attached screenshot and log output.

```
name:      noson
summary:   The essential to control music from your SONOS devices
publisher: Jean-Luc Barriere (janbar)
store-url: https://snapcraft.io/noson
contact:   jlbarriere68@gmail.com
license:   unset
description: |
  The fast and smart controller for your SONOS devices on Ubuntu platform. You can browse your music
  library and play track, radio or internet stream on any zones. You can manage zone groups, queue
  and playlists and fully control the playback.
commands:
  - noson
snap-id:      d7aPr2121k98JGTTE8UTebzNrSUZhIXh
tracking:     latest/stable
refresh-date: 20 days ago, at 10:20 PDT
channels:
  latest/stable:    4.3.3.snap 2020-05-06 (339) 97MB -
  latest/candidate: ↑                                
  latest/beta:      ↑                                
  latest/edge:      4.3.3.snap 2020-05-06 (339) 97MB -
installed:          4.3.3.snap            (339) 97MB -

```

![Screenshot from 2020-05-31 13-31-28](https://user-images.githubusercontent.com/1082030/83362142-cb780c00-a343-11ea-90f0-151b4547609e.png)

[noson.log](https://github.com/janbar/noson-app/files/4708363/noson.log)

**Comment by janbar** [comment]
Hi, something weird in log. The scale setting seems to be zero.

There is the settings file which store the scale values:
- using the "native" app: the file is ```~/.config/janbar/io.github.janbar.noson.conf```
- using the snap app the file should be:
```~/snap/noson/current/.config/janbar/io.github.janbar.noson.conf```

Check the value of "fontScaleFactor" and "scaleFactor". The default is 1 to scale x1. I guess one of them is 0 in your case.

**Comment by janbar** [comment]
Using a screen 4k , you have probably set the display scale to 200%. That's ok, I have the same setting and it works. But you have to check you haven't set the QT_SCALE_FACTOR or any other settings in your ".profile" that is influencing the factor. Also I saw a bunch of errors in the log related to a resizing to 0. It could be the root cause and I don't know how is possible, unless a special setting is used as QT_SCALE_FACTOR. Something odd ...

**Comment by shawnburke** [comment]
Hi - thanks so much!  Yes, changed those to 1 and all was good. Not sure how that got set to zero, maybe a bug there.

I don't have the QT setting.

Thanks again for quick turnaround!
