### ISSUE TITLE
Unable to browse or change the active Plex library

### ISSUE THREAD

**Issue by bmn001** [janbar/noson-app#136]
I have two Plex libraries.

Noson will show the first one by default.  When I click "Other Sources" within the Plex panel of Noson to select the other library, Noson spins for a bit and then presents a blank panel.

**Comment by janbar** [comment]
Activating debug output, you will see what happens.

**Comment by bmn001** [comment]
It looks like a recent (this week) update to Plex media server has fixed this behavior.
