### ISSUE TITLE
Feature request: "Update Music Library Now"

### ISSUE THREAD

**Issue by EmptyStackExn** [janbar/noson-app#137]
Hello, this is great work! I am using the CLI version as it handy to automate tasks. Is there a way to reindex the music library with the CLI as it is [necessary in Sonos](https://support.sonos.com/s/article/2401?language=en_US) ? For instance, this is done in [node-sonos-http-api](https://github.com/jishi/node-sonos-http-api) as `reindex` command.

**Comment by janbar** [comment]
Yes it can be added as a new command in the CLI.
Until now I made the CLI to manage the queue of zone, and I voluntary missed any command to manage the library. First reason is because that should include the command(s) to browse the library. This job is much easier to do using the app.

**Comment by janbar** [comment]
I added the command by the commit fe51796842a97ffb7765f449423a310d271587a0.

**Comment by EmptyStackExn** [comment]
Thanks! This is great!
