### ISSUE TITLE
Can't find Sonos on Ubuntu 16.10

### ISSUE THREAD

**Issue by NewtoUbuntu** [janbar/noson-app#14]
Loaded Noson to use with my exciting Sonos set up but Noson said it can't find my Sonos network.
Terminal says this. 

Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
(SONOS)Process: bind port 1400
qml: Zones_QMLTYPE_172(0x1d80260): In Ubuntu.Components 1.3, the use of Page.title, Page.flickable and Page.head is deprecated. Use Page.header and the PageHeader component instead.
(SONOS)registerModel: 0x1efe110 (Q:0)
qml: Debug: LANG=en_US

any help would be appreciated

**Comment by janbar** [comment]
Could you try to launch noson with flag "--debug" to show what's happen ?

**Comment by janbar** [comment]
I upgraded verbosity when discovering sonos devices, with version 2.4.12. Please upgrade to the new version and post again the begining of output including lines starting with `(SONOS)FindDeviceDescription:`, as follows.

    (SONOS)FindDeviceDescription: starting new context
    (SONOS)FindDeviceDescription: location url found (http://192.168.0.193:1400/xml/device_description.xml)
    (SONOS)FindDeviceDescription: server string found (Linux UPnP/1.0 Sonos/37.2-44160 (ZP120))
    (SONOS)FindDeviceDescription: search target matches (urn:schemas-upnp-org:device:ZonePlayer:1)
