### ISSUE TITLE
Error when trying to switch to night mode

### ISSUE THREAD

**Issue by earthwalker31** [janbar/noson-app#156]
Whenever I try to activate night mode in the sound settings I get the error: Action can't be performed
![image](https://user-images.githubusercontent.com/56949417/104812342-c4820900-5801-11eb-9261-67c0aed07622.png)

The console output is:
```
(SONOS)WSResponse: server error (500)
(SONOS)Request: invalid response
```
I built the newest version available (4.4.7)

My os version:
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
PRETTY_NAME="Pop!_OS 20.10"
ID_LIKE="ubuntu debian"
UBUNTU_CODENAME=groovy

**Comment by janbar** [comment]
Hi, night mode isn't enable for all Sonos devices. For instance it is available only with the device Sonos Playbar.

**Comment by earthwalker31** [comment]
This seems to be a Sonos issue. It worked again after rebooting my Playbar.
