### ISSUE TITLE
Noson fails to start on Ubuntu 20.10

### ISSUE THREAD

**Issue by ericsgroove** [janbar/noson-app#157]
Ubuntu 20.10 / Gnome 3.38

noson --debug 2>&1 | tee noson.log

_Qt: Session management error: Could not open network socket
Signal handler is enabled.
"using file ':/i18n/noson_en.qm ' for translations."
Fontconfig warning: FcPattern object weight does not accept value [49,9673 210)_

**Comment by janbar** [comment]
How you installed the app ?

**Comment by ericsgroove** [comment]
> How did you install the app ?

Directly from the Ubuntu / Snap store.

**Comment by janbar** [comment]
You should install the native app from my PPA instead a SNAP which is often buggy, as follows.

sudo add-apt-repository ppa:jlbarriere68/noson-app
sudo apt-get update

# remove the snap app...
sudo snap remove noson

# Install the native app
sudo apt install noson-app

**Comment by ericsgroove** [comment]
> You should install the native app from my PPA instead a SNAP which is often buggy, as follows.
> 
> sudo add-apt-repository ppa:jlbarriere68/noson-app
> sudo apt-get update
> 
> # remove the snap app...
> sudo snap remove noson
> 
> # Install the native app
> sudo apt install noson-app

That worked! Thank you!
