### ISSUE TITLE
UI Threading issues

### ISSUE THREAD

**Issue by hooperbloob** [janbar/noson-app#17]
I love that I can now use Sonos on Ubuntu but the UI could use some tweaks to address usability.

* threading - (lack thereof?)  
       Upon startup it sits there, unresponsive to the mouse (for up to 30 seconds) and no indication that anything is going on until it comes back and populates the window with album covers.  Would suggest displaying a previously cached set of titles/images and showing an activity indicator.  
    When resizing the window, its unable to redraw the contents for several seconds.
    Is the circle with orange segments intended to be an activity indicator?  If so, then I suggest  animating it.

* multi-selection
    I'd like to be able to select multiple items in the main window and perform actions on them as a group per options in a context menu. Ditto for the queue (i.e. group Remove)

 * additional columns
   Providing additional columns with metadata would be really great.  Then songs in playlists could be sorted by genre, playing time, artist name, etc.

* instant actions  (nice to have)
   having to right-click items in the queue, find the Remove item, then click it is cumbersome. Suggest providing buttons that appears under the mouse when it hovers over an item. [play] [delete] [queue]   etc..

**Comment by janbar** [comment]
Hi, the app has been designed for touch screen. So you have to use gesture
with mouse to enable what you need: flick left, flick right, flick up/down,
click and hold, etc.
All features you mentioned exist. Just use gesture.
About multi-threading, yes the app uses a lot. But it depends of graphical
capabilities of your desktop. The UI had been writen in Qt-qml and
graphical animations are controled by the qml runtime which requires 3D
capabilities.

**Comment by janbar** [comment]
Currently I am refactoring the app to use the latest Qt framework, and so no longer using the ubuntu sdk which has been broken since the ubuntu 17.10. In few weeks a new version will be out and it will be better on desktop without gesture.

**Comment by janbar** [comment]
I refactored the app for Ubuntu 17.10 and later. No SNAP package is available for this version. You have to install the deb package from my PPA.
A SNAP package could be available once 18.04 is out (April 2018). But you should prefer the native package from my PPA.

**Comment by janbar** [comment]
Fixed with version 3.0.
Now many functions are available without gesture and some blocking operations have been pushed in the thread pool to be processed in the background, instead running synchronously.
