### ISSUE TITLE
#!/usr/bin/env bash in noson-app.in not necessary?

### ISSUE THREAD

**Issue by herrhotzenplotz** [janbar/noson-app#170]
A little thing I noticed on FreeBSD 13.0-RELEASE-p4:

The official port has no apparent dependency on bash which I do not have installed.
Thus when I try to start `noson-app` it fails with a message that bash wasn't found.

Looking at the little script, I cannot see any serious bashisms, so maybe the hashbang can be changed to a simple `#!/bin/sh`. It works very much fine here on FreeBSD. 
However, I have no idea whether it breaks other systems because I cannot test it, but I suggest changing that line, as it would get rid of the direct runtime dependency on bash.

**Comment by janbar** [comment]
You are right "bash" isn't required. Fixed.

**Comment by herrhotzenplotz** [comment]
Thank you!
