### ISSUE TITLE
Upgrade from Freedesktop SDK 18.08

### ISSUE THREAD

**Issue by AntonOellerer** [janbar/noson-app#172]
Hey,
Thank you very much for this tool, it is really superb when employing a sonos system!
I am using the tool on fedora 35, installed via flatpak.
Whenever I run `flatpak update io.github.janbar.noson`, I get the warning 
```
Info: org.freedesktop.Platform.html5-codecs//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
```
Would it be possible to fix this?
I would try it myself, but I have not found the correct place yet.
Best regards
Anton

**Comment by janbar** [comment]
Please see https://github.com/flatpak/flatpak/issues/3531

**Comment by AntonOellerer** [comment]
Ah, thank you!
