### ISSUE TITLE
Cannot connect to pipewire

### ISSUE THREAD

**Issue by AntonOellerer** [janbar/noson-app#175]
Hey,
First of all, thank you for this nice project!
I am currently running into issues when trying to use noson for streaming sound from my laptop via pipewire.
When I activate the `PulseAudio` button, the UI changes, but the sink does not show up in the sound control gui, and journalctl shows me the following messages:
```
Feb 02 12:08:43 fedora io.github.janbar.noson.desktop[1357889]: (SONOS)streamSink: no sink availableqml: Set queue position view at -1
Feb 02 12:08:43 fedora wireplumber[1295353]: <WpSiAudioAdapter:0x55d899e67610> Object activation aborted: proxy destroyed
Feb 02 12:08:43 fedora wireplumber[1295353]: <WpSiAudioAdapter:0x55d899e67610> failed to activate item: Object activation aborted: proxy destroyed
```
Do you know what the problem is here?
I already looked through https://github.com/janbar/noson-app/issues/159, but I did not really find concluding information there.

* I am using fedora 35, 
* the problem is occurring both in the flatpak and the locally-built distribution, version 4.5.2.
* libpipewire 0.3.44
* wireplumber 0.4.7
* pipewire-pulseaudio 0.3.44

Best regards
Anton

**Comment by janbar** [comment]
I have no clue about "pipewire". The app use the standard API of pulseaudio to create its sink. Seems "pipewire" isn't fully compatible with pulseaudio.

**Comment by janbar** [comment]
If you know C/C++ , you could try to hack the source code to investigate what happen with pipewire. the corresponding source code is here: https://github.com/janbar/noson/blob/master/noson/src/pacontrol.cpp (libnoson).

**Comment by AntonOellerer** [comment]
Thanks for the tip, I will take a look at it when I have some time!

**Comment by janbar** [comment]
The app is linked with "libpulse.so" and "libpule-simple.so" , not the pipewire wrapper for pulse. That could explains why it cannot initiate the sink.
To fix the issue I have to dynamically load the lib depending of the installed libs: libpulse or the pipewire wrapper. In the master branch I added a commit to load dynamically libpulse.

**Comment by janbar** [comment]
@AntonOellerer , I succeeded make it work with pipewire. Let me little more time to understand what's happen ...

**Comment by janbar** [comment]
I fixed the issue by the commit https://github.com/janbar/noson/commit/b4fb89bc4a3904ac556e4dc12a4ed6398efb27a3.
The new release 5.0.5 include the fix.

**Comment by AntonOellerer** [comment]
Hey,
I have only been able to run a quick test now with the flatpak package, but I was able to redirect the audio to the noson sink, and consequently to the sonos speaker, so it seems to work now, thank you very much!
If you are interested, I can inspect it more thoroughly and/or with the package built version.

**Comment by janbar** [comment]
Yep, I found the issue in the flatpak package. The resolver did'nt find the lib libpulse.so. Instead I have to load the lib libpulse.so.0. So now it should work as expected.
Thanks reporting this issue, and let me know if you face an other bug.

**Comment by AntonOellerer** [comment]
Thank you a log :pray:
