### ISSUE TITLE
AppImage build

### ISSUE THREAD

**Issue by moppman** [janbar/noson-app#177]
Hi, 
would you consider providing  AppImage releases, maybe using e.g. [this](https://appimage-builder.readthedocs.io/en/latest/hosted-services/github-actions.html)?
Thanks!

**Comment by janbar** [comment]
Awesome. You will find the App image in the releases section: https://github.com/janbar/noson-app/releases/download/5.0.6/noson-app-5.0.6-x86_64.AppImage

Now I stop definitively to maintain the snap package ... a bullshit and nothing work properly after a ton of spent time.

Thanks !

**Comment by janbar** [comment]
Ah, I will check that soon

**Comment by janbar** [comment]
It should be fixed. I uploaded the fixed image.

**Comment by moppman** [comment]
Yes, seems like it's working fine!
Again, thank you so much :heart:
