### ISSUE TITLE
Currently playing info no longer displays

### ISSUE THREAD

**Issue by ralphka** [janbar/noson-app#180]
![noson](https://user-images.githubusercontent.com/100437044/155765962-966f9b2e-1640-4189-938b-9e98676be8e1.png)
TuneIn station currently playing title/info no longer displays since 5.0.8 or thereabouts.  Sonos client on windows and iPhone display the info correctly.   Example, TuneIn, Colorado Public Radio Classical.

Thanks for your good work on this project.

**Comment by janbar** [comment]
Seeing your screenshot, I anderstood. That because you activated the wide view. In normal view the infos are showing:

![Capture d’écran du 2022-02-25 20-02-16](https://user-images.githubusercontent.com/2353635/155773054-dcdb0e5f-6700-4cc8-bbc2-9269d46b30f9.png)

**Comment by janbar** [comment]
So I have to make some little place under the control to show current playing.

**Comment by ralphka** [comment]
Wide view?  Normal view?  Where are those settings?    As mentioned, until a recent update, this info display was visible.   Thanks for the prompt reply!

**Comment by janbar** [comment]
Wide view is activated when you enlarge the width of the window. In this case the player control is shown in right column.
If you educe the width of the window, the view move to normal: to show player controls , you have to click on the footer (mini player control).

**Comment by janbar** [comment]
I fixed it like below.

![Capture d’écran du 2022-02-25 22-21-03](https://user-images.githubusercontent.com/2353635/155804652-a806ae86-a9bf-4395-a9ac-4f1d7048bff4.png)

**Comment by ralphka** [comment]
Aha, **shrinking** the window solves the problem completely.  The playing source and music info vanish completely when the window is expanded.  Thanks!  Attachments illustrate.
![visible](https://user-images.githubusercontent.com/100437044/155812528-c92d5a78-92f7-4102-afdf-af7d1fb90980.png)
![vanish](https://user-images.githubusercontent.com/100437044/155812530-438936d4-ae65-43d1-a2c1-959c3d8ac327.png)

**Comment by ralphka** [comment]
Github newbie....   issue closed/solved for me, but discussion can remain for anyone.  Thanks again!

**Comment by ralphka** [comment]
5.1.2 fixes it for any window size.  Thanks!
