### ISSUE TITLE
"Favorites" no longer showing up (v5.3.0)

### ISSUE THREAD

**Issue by moppman** [janbar/noson-app#192]
Hi,
it seems like the new "My Radios" category has replaced the "Favorites" category.

Assuming this is not intended behavior, [this change](https://github.com/janbar/noson-app/commit/fe5a5bbbd95f9ad94506669dd5d8a6dd3a3352c5#diff-b967c724f87ca1da3b8502e59643642bfd26d6071e263a9b7c81a327598a1d9aR819) looks like the nost likely culprit.

Thanks!

**Comment by janbar** [comment]
Thanks for reporting. I fixed it by commit d2e27fe2c285ac09911e93930501a812f31ff830

**Comment by moppman** [comment]
Thanks for the quick fix!
