### ISSUE TITLE
Crash with no obvious error message, possibly caused by Spotify serving lores cover art now 

### ISSUE THREAD

**Issue by hzulla** [janbar/noson-app#195]
Noson 5.3.2 here.

Spotify playback used to work fine and thanks to the discussion of #194, I was able to have a big cover art display, too.

However, since today, cover art is pixelated (incomplete JPEG download?)...

![Bildschirmfoto vom 2022-10-14 12-00-28](https://user-images.githubusercontent.com/1705654/195820803-1aac311c-9674-4e11-bf5c-4828366ff1ec.png)

...and when I change Noson's window size, the application will crash without an error message.

I tried looking into the debug log, but found no obvious error message.

**Comment by hzulla** [comment]
Very weird. Also seeing blurry cover art in the Android Sonos App when playing Spotify music. So this isn't specific to Noson.

![Screenshot_20221022-125850~2](https://user-images.githubusercontent.com/1705654/197335533-86c0f937-a1ce-4956-9119-946f175d8107.png)

**Comment by hzulla** [comment]
Okay, so it's a known problem on Spotify's end and they are working on it.

https://en.community.sonos.com/music-services-and-sources-228994/spotify-album-artwork-is-distorted-6876690

So the pixelated cover art isn't Noson's fault.

This still leaves the question why Noson keeps crashing here on my system and how to give a more helpful debug log about that to you.

**Comment by hzulla** [comment]
@janbar The cover art is back to normal and Sonos confirmed in the thread linked above that Spotify resolved the issue on their side.

I'm also not seeing Noson crashing anymore, too.

Closing this now, but still the question remains why the pixelated images apparently caused Noson to crash. I would have expected Noson to just display blurred art without crashing over them.

**Comment by hzulla** [comment]
Once again, thanks for the application!

**Comment by janbar** [comment]
The root cause of the crash could be an invalid image format. Noson doesn't handle directly the images. The app uses the Qt5 framework to handle these things.
