### ISSUE TITLE
CR: pulse-audio setting does not output desktop audio on Symfonisk speakers

### ISSUE THREAD

**Issue by leder11011** [janbar/noson-app#201]
Hello Janbar,
can you please elaborate on the function of the setting "pulse-audio"?!
I would like to output my desktop audio to sonos.
Thanks alot!
Best regards
Gerrit

**Comment by ralphka** [comment]
On 4/23/23 02:36, leder11011 wrote:
> Hello Janbar,
> can you please elaborate on the function of the setting "pulse-audio"?!
> I would like to output my desktop audio to sonos.
> Thanks alot!
> Best regards
> Gerrit
> 

Hi Gerrit -- This works for me:

~$ run noson --cli
Noson CLI using libnoson 2.10.0, Copyright (C) 2018 Jean-Luc Barriere
Searching... (SONOS)Bind: could not bind to address (98)
Succeeded
Found player 'Family Room' with UUID 'RINCON_94xxxxxxxxx'
Found zone 'Family Room' with coordinator 'Family Room'
 >>> connect Family Room
Connected to zone Family Room
Family Room >>> playpulse
Succeeded
Family Room >>>

 From pavucontrol you can select the speaker.  I adjust the volume from 
the noson gui.

Hope this helps.

Ralph

**Comment by leder11011** [comment]
feature added to gui settings recently
