### ISSUE TITLE
Ubuntu PPA unmet dependencies

### ISSUE THREAD

**Issue by manikandancode** [janbar/noson-app#207]
Ubuntu 23.04 Wayland.

![Screenshot from 2023-09-28 16-13-42](https://github.com/janbar/noson-app/assets/46480489/6ca7947e-234a-4057-be67-179ece364150)

**Comment by janbar** [comment]
I checked the buildlog of Mantis(23.04) from landscape and it shows me:

depends: libflac++10 (>= 1.3.1), libflac12 (>= 1.3.0)

So my debian control file has an issue ...

**Comment by janbar** [comment]
The new build for Lunar and Mantic are pending. It should be fixed in a couple of minutes.
