### ISSUE TITLE
Setting up a development environment

### ISSUE THREAD

**Issue by southernsun** [janbar/noson-app#216]
Being new to QT development, but being a developer myself, do you have some pointers on where and how to start to setup a development environment? what IDE would you recommend or are you using? What is the best way to debug the application? Any guidance would be nice. Perhaps you can enable WIKI on this GitHub repository so people (like me) can add useful information such as how to setup a dev environment.

Thanks!

**Comment by janbar** [comment]
Use Qt creator latest version, and Qt 5.15. Then open the CMakeLists.txt and finally press the button "Compile" ...
