### ISSUE TITLE
Property 'clear' of object MediaModel is not a function

### ISSUE THREAD

**Issue by jagaudin** [janbar/noson-app#22]
Thanks for the great Sonos app. All your hard work is **much appreciated**!

I have successfully built noson-app on Arch linux and thought I would do a package for it. The only issue I have so far is with the Spotify service authorization. 
On the service page when I click on my Spotify account, I don't get the authorization link, just a blank page with the Spotify logo blurred in the background.

I have looked into this issue and found this error message:

    qrc:/ui/Service.qml:361: TypeError: Property 'clear' of object MediaModel(0x563052c7be90) is not a function

Looking into the source, it seems that in `Service.qml` line 361, `mediaModel.clear()` is called. But if I look at `mediamodel.cpp`, the closest function I have is `MediaModel::clearData()`.

Could this be the origin of the problem?

Note that I have also tried installing the snap package which works fine with Spotify. Looking at the source of `Service.qml` in Snap v2.6, the function call is `mediaModel.clearData()`.

**Comment by jagaudin** [comment]
I can confirm that changing `mediaModel.clear()` to `mediaModel.clearData()` fixes the issue. I created a PR for this. #23

**Comment by janbar** [comment]
Yes you re right, it must call clearData instead.
