### ISSUE TITLE
.flac files w/ 96 kHz sample rate not working.

### ISSUE THREAD

**Issue by droj73** [janbar/noson-app#229]
Hello again, Jean-Luc.

Thank you for your help earlier.
I have noticed that .flac files w/ sample rates of 96 kHz have trouble playing.

Are these going to be supported in the near future?

Thank you.

**Comment by janbar** [comment]
Hi, the Sonos devices (Gen 1) didn't support 96k. And probably the Gen 2 doesn't support it.

If you use the "pulse" feature of Noson, the app converts the stream to flac 16/44.1k. But it doesn't downgrade, first because downgrading needs filtering and dithering.

**Comment by droj73** [comment]
Hi Jean-Luc,

Thank you for your response.  I do appreciate your time.
I have been able to work around this limitation with the Linux  sox  utility (w/ the  '-r 44100'  switch).
It does convert the .flac from a 96k to a 44.1k sample rate, (and my ears can not tell the difference).
Works for me!

Thank you again, for such an awesome app!
Don
