### ISSUE TITLE
Update to Sonos 40.5-49090 breaks query accounts

### ISSUE THREAD

**Issue by jagaudin** [janbar/noson-app#24]
It seems that since the latest update of Sonos to 40.5.49090, `LoadAccounts` in `musicservices.cpp` is failing, resulting in Spotify not being displayed anymore in *My Services*

The log is the following:

    (SONOS)__connectAddr: connected to socket(0x5566a2bc6058)
    (SONOS)SendRequest: GET /status/accounts HTTP/1.1
    Host: 192.168.0.184:1400
    User-Agent: libnoson/1.0
    Connection: close
    Accept-Charset: utf-8
    Accept-Encoding: gzip, deflate

    (SONOS)GetResponse: HTTP/1.1 200 OK
    (SONOS)GetResponse: CONTENT-TYPE: text/xml
    (SONOS)GetResponse: Server: Linux UPnP/1.0 Sonos/40.5-49090 (ZP90)
    (SONOS)GetResponse: Connection: close
    (SONOS)GetResponse: 
    (SONOS)ReceiveData: socket(0x5566a2bc6058) timed out (0)
    (SONOS)ReceiveData: socket(0x5566a2bc6058) timed out (1)
    (SONOS)ReceiveData: socket(0x5566a2bc6058) timed out (2)
    (SONOS)ReceiveData: socket(0x5566a2bc6058) timed out (3)
    (SONOS)ReceiveData: socket(0x5566a2bc6058) timed out (4)
    (SONOS)ReceiveData: socket(0x5566a2bc6058) timed out (5)
    (SONOS)ReceiveData: socket(0x5566a2bc6058) timed out (0)
    (SONOS)ReceiveData: socket(0x5566a2bc6058) timed out (1)
    (SONOS)ReceiveData: socket(0x5566a2bc6058) timed out (2)
    (SONOS)ReceiveData: socket(0x5566a2bc6058) timed out (3)
    (SONOS)ReceiveData: socket(0x5566a2bc6058) timed out (4)
    (SONOS)ReceiveData: socket(0x5566a2bc6058) timed out (5)
    (SONOS)LoadAccounts: invalid or not supported content
    (SONOS)<?xml version="1.0" ?>
    <?xml-stylesheet type="text/xsl" href="/xml/review.xsl"?>
    <ZPSupportInfo/>

    (SONOS)GetEnabledServices: query accounts failed

The above seem to indicate that the test in `musicservices.cpp` line 361 fails:

    if (!(elem = rootdoc.RootElement()) || !XMLNS::NameEqual(elem->Name(), "ZPSupportInfo")
          || !(elem = elem->FirstChildElement("Accounts")))

I think the `elem = elem->FirstChildElement("Accounts")` returns false because there is no Accounts in the xml response. 

Is it due to Sonos changing the way to retrieve Accounts?

In a browser if I go to `http://192.168.0.xxx:1400/status` there is no accounts link available. Was there one before the update?

Please let me know if I can be any help.

**Comment by janbar** [comment]
Thanks for report the issue. I haven't yet upgrade my sonos devices to this version. It seems I have to change the way to know registered accounts. The app stores already the list of accounts with credentials but it has nothing for those with free access. I let you know soon aboit.

**Comment by janbar** [comment]
@jagaudin , I updated the app to manage accounts locally. I haven't yet upgraded my devices so I can test with old firmware version of sonos. It should work with the new now. Please let me know.

**Comment by jagaudin** [comment]
@janbar thanks a lot! I am away until Monday night but I will definitely test and report once I'll be back home.

**Comment by jagaudin** [comment]
It works like a charm. Thanks!
