### ISSUE TITLE
Replace queue

### ISSUE THREAD

**Issue by papertigers** [janbar/noson-app#29]
New feature request.

The official Sonos apps let you replace the queue with new content.  Right now my workflow is to click the menu on the bottom right -> Manage queue -> CLEAR QUEUE.  Followed by "Play all" on the album I am trying to queue up.

It would be nice if on the album screen there was a "Replace queue" option.

**Comment by janbar** [comment]
Possible to do: pressing "play" on a bundle (album, playlist) will replace queue content.
It will continue to append queue playing a song, or obviously queueing something.

**Comment by janbar** [comment]
Fixed in version 3.3.0

**Comment by papertigers** [comment]
Just tested this and issue #28 
Works great! Thanks again for all the hard work!
