### ISSUE TITLE
Playback stopping Linux Mint

### ISSUE THREAD

**Issue by george1955** [janbar/noson-app#32]
Hi
I've installed Noson on Linux Mint. When playing back the music will stop mid stream and the player becomes temporarily unresponsive. I tried changing the wireless channel on my router but this had no effect and the play still stops. I thn ran using noson-app --debug 2>&1 | tee noson.log and I have attached a logfile and hope that you can help.
Thanks

George

[noson.txt](https://github.com/janbar/noson-app/files/1981942/noson.txt)

**Comment by janbar** [comment]
I can't reproduce the case. Is using "skip back" to the previous track ?

**Comment by george1955** [comment]
Hi.
Apologies for the delay. Problem seems to be resolved. I changed the wireless channel for Sonos on my router and it seems to be ok now.
Thanks
