### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Vostro162** [janbar/noson-app#4]
here is my German Translation 
https://gist.github.com/Vostro162/87e12497da72e67c84d4

**Comment by janbar** [comment]
Thanks Marius. Your translations will be online with version 1.3.3 by one
hour.

2016-03-08 14:17 GMT+01:00 Marius <notifications@github.com>:

**Comment by janbar** [comment]
Later you could update your translations from transifex https://www.transifex.com/janbar/noson/dashboard/ .  To enable your transifex account for the project you will have to send me a valid email address, and then i will be able to register you.

**Comment by Vostro162** [comment]
okay this is my email marius.hartig@googlemail.com
i found a couple of misspelling i will fixing that for the next version

**Comment by janbar** [comment]
I invited you to the transifex project
