### ISSUE TITLE
qt5_use_modules is deprecated

### ISSUE THREAD

**Issue by papertigers** [janbar/noson-app#40]
Attempting to build this on archlinux blows up with
`
CMake Error at gui/CMakeLists.txt:42 (qt5_use_modules):
  Unknown CMake command "qt5_use_modules".
`

It appears `qt5_use_modules` has been replaced with `target_link_libraries`

**Comment by janbar** [comment]
fixed by commit 32987dd373f1643d7de287f9aa480aa145794c9d
