### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by Vostro162** [janbar/noson-app#5]
can you create a Gitter Chat for a good conversation about the app ?

**Comment by janbar** [comment]
I added the gitter badge on repo and project page.
project
Le lundi 14 mars 2016, Marius <notifications@github.com> a écrit :
> can you create a Gitter Chat for a good conversation about the app ?
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci6.googleusercontent.com/proxy/j8vS2Dv6bxSCEHq2s2cphX6nNLvcAzp9jB64dspDmrCylIPdzpiVktDdcJEKgtgP-jVKe6AyHbhmfKZ3ay-b52XIqu55wkoYY3Leq_3FcxsGjSyfLdg-ZCF8fDvYEwDABZOlSpzBF4kbiTW7L26fiFdh0-Rmbw=s0-d-e1-ft#https://github.com/notifications/beacon/ACPp43ijZgkghIu7l1p5hBAlMhksgxsyks5ptVzngaJpZM4HwB5_.gif
>
