### ISSUE TITLE
Service authentication URL can't be copied to clipboard

### ISSUE THREAD

**Issue by callahad** [janbar/noson-app#50]
When attempting to add Amazon Music (see bug #48), Noson asked me to click an OAuth link. However, the link displayed in Noson was incomplete (it only showed the `client_id` parameter, not all the additional OAuth stuff), and it wasn't possible to copy it to the clipboard.

I use a different browser profile for Amazon stuff, and this made it impossible to open the authentication link in the correct browser. To work around it, I had to temporarily change my default browser.

**Comment by janbar** [comment]
You have to click the link to open the default browser. No way to choose which browser: this should be handled by the gui manager.
