### ISSUE TITLE
Plex service never loads any content served from Plex server

### ISSUE THREAD

**Issue by netllama** [janbar/noson-app#53]
After adding the Plex service, none of the content actually provided by my local Plex server is shown.  All I get is the default content hosted by the Plex (cloud) service (Podcasts, News, Comedy, etc).

**Comment by netllama** [comment]
The only thing I see after 'Other Sources' is 'Podcasts'.

**Comment by janbar** [comment]
Have you enabled the remote access of your Plex ?

**Comment by netllama** [comment]
Plex works fine with the official Sonos app.

**Comment by janbar** [comment]
Can't be reproduced. Also the issue relates a bug in Plex service, not this app.

**Comment by netllama** [comment]
You're saying that your approach to bug reports is to close them if you can't reproduce them??  Its not a bug unless you can reproduce it?

**Comment by janbar** [comment]
I tested the plex service and it works well. I can retrieve my plex server. Also to work I had to enable remote access. So I guess the issue is in your plex configuration or maybe caused by network issue.

**Comment by netllama** [comment]
Plex works fine for me with everything but your app.  It works via the Sonos App.  It works via the Plex app.  

If you feel that the problem is my plex configuration or some (undefined) network issue, then please provide details on what needs to be corrected.  At this point, your app is the only thing that's failing to work, which suggests a bug in your app.
