### ISSUE TITLE
cosmic build

### ISSUE THREAD

**Issue by sbeckeriv** [janbar/noson-app#59]
```
sudo add-apt-repository ppa:jlbarriere68/noson-app
...

E: The repository 'http://ppa.launchpad.net/jlbarriere68/noson-app/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by janbar** [comment]
I am fixing that...

**Comment by janbar** [comment]
It is currently building on launchpad ppa: https://code.launchpad.net/~jlbarriere68/+recipe/noson-app-daily

**Comment by sbeckeriv** [comment]
Thanks I tried downloading the deb file and installing it via Eddy. it says it cant install qttranslations5-l10n but apt install says i have the latest. I will try again later. 

Thanks again,
Becker

**Comment by sbeckeriv** [comment]
command line worked fine. thank you again!
