### ISSUE TITLE
(SONOS)FindDeviceDescription: search target not matches

### ISSUE THREAD

**Issue by r7xf** [janbar/noson-app#62]
Hai, the app works good but there seems to be some issues connecting to the Sonos device.
Log: 

Signal handler is enabled.
"using file ':/i18n/noson_en.qm ' for translations."
installing thumbnails cache in folder "/home/user/.local/share/janbar/noson/QML/OfflineStorage"
thumbnailer Last.fm is initialized
qml: LANG=en_US
thumbnailer: configure key []
(SONOS)ReceiveData: socket(0x7f1842ffcbd8) timed out
(SONOS)ReceiveData: socket(0x7f1842ffcbd8) timed out
(SONOS)ReceiveData: socket(0x7f1842ffcbd8) timed out
(SONOS)ReceiveData: socket(0x7f1842ffcbd8) timed out
(SONOS)ReceiveData: socket(0x7f1842ffcbd8) timed out
(SONOS)ReceiveData: socket(0x7f1842ffcbd8) timed out
(SONOS)ReceiveData: socket(0x7f1842ffcbd8) timed out
(SONOS)ReceiveData: socket(0x7f1842ffcbd8) timed out
(SONOS)ReceiveData: socket(0x7f1842ffcbd8) timed out
(SONOS)ReceiveData: socket(0x7f1842ffcbd8) timed out
(SONOS)unregisterModel: 0x56320cac52c0 ()
(SONOS)unregisterModel: 0x56320cd544a0 (Q:0)
(SONOS)unregisterModel: 0x56320cd5bef0 ()
(SONOS)unregisterModel: 0x56320cd5afd0 ()
(SONOS)unregisterModel: 0x56320cd5ce10 ()
(SONOS)unregisterModel: 0x56320cd5a020 (FV:2)
(SONOS)unregisterModel: 0x56320cd55380 (SQ:)
(SONOS)Stop: event handler thread (0x56320cd12420)
(SONOS)__connectAddr: connected to socket(0x56320d063918)
(SONOS)SendRequest: HEAD / HTTP/1.1
Host: 127.0.0.1:1400
User-Agent: libnoson/1.0
Connection: close
Accept-Charset: utf-8
Accept-Encoding: gzip, deflate

(SONOS)Process: accepting new connection
(SONOS)AnnounceStatus: (0x56320cd12420) STOPPED
(SONOS)ParseQuery: HEAD / HTTP/1.1
(SONOS)ParseQuery: Host: 127.0.0.1:1400
(SONOS)ParseQuery: User-Agent: libnoson/1.0
(SONOS)ParseQuery: Connection: close
(SONOS)ParseQuery: Accept-Charset: utf-8
(SONOS)ParseQuery: Accept-Encoding: gzip, deflate
(SONOS)ParseQuery: 
(SONOS)GetResponse: HTTP/1.1 200 OK
(SONOS)GetResponse: CONTENT-TYPE: text/html
(SONOS)GetResponse: CONTENT-LENGTH: 101
(SONOS)GetResponse: 
(SONOS)Stop: event handler thread (0x56320cd12420) stopped
(SONOS)Stop: subscription thread (0x56320cd12128:1)
(SONOS)Stop: subscription thread (0x56320cd12128:1) stopped
Signal handler is destroyed.

**Comment by janbar** [comment]
Your log shows the app didn't receive a response from a sonos device.
When a device has been fished the response look like the following:

    thumbnailer: configure key [...]
    (SONOS)FindDeviceDescription: starting new context
    (SONOS)FindDeviceDescription: location url found (http://192.168.2.113:1400/xml/device_description.xml)
    (SONOS)FindDeviceDescription: server string found (Linux UPnP/1.0 Sonos/45.1-56150 (ZP120))
    (SONOS)FindDeviceDescription: search target matches
    ...

Any firewall ?

**Comment by r7xf** [comment]
> Any firewall ?
Thats the strange part; when the firewall is disabled it still does not work, I just tested the unofficial-sonos-controller by pascalopitz and that app does seem to be able to find||connect to the sonos device. I know i cant compare the two apps as theyre totally different but that seems to rule out the firewall obstruction i think. I just cant seem to figure out why it wont find the device.

**Comment by r7xf** [comment]
Thanks for getting back to me I took some time to figure it out, even build it from source to make sure everything was up to date.
When went to your comment again I realized I forgot to check the router and after adding some new rules I managed to get it working. Thanks again!
