### ISSUE TITLE
Focus@Will - Can't correct logon info

### ISSUE THREAD

**Issue by ccregor** [janbar/noson-app#63]
Got my credentials in wrong the first time, got 'em right the second time.
Focus@Will creates a blank page with enlarged icon as the background and just sits there.
Created a second Focus@Will, which didn't ask me credentials and has the same behavior.
Read UI bit about hitting the list button to get the remove. Removed both Focus@Will services.
Added a new one, again was not asked credential, again got a blown up icon as background and nothing else....

Great app by the way! But, help!!!!

**Comment by janbar** [comment]
Which version of noson ? V2 or V3.

**Comment by ccregor** [comment]
V2 from stable channel
stable:    2.8.7.snap-1 (160) 172MB - <

**Comment by janbar** [comment]
I tried the service but first call failed with error below:
`SSL connect failed: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure`
That's probably the first cause of the issue.

**Comment by janbar** [comment]
I have a fix for SSL issue. Still to release out.

**Comment by ccregor** [comment]
Cool!

**Comment by ccregor** [comment]
K this is great!
Got the snap problem you posted. Checked out flatpak (which seems better than snap so far, but thats first impression only). v3 of noson is slick!!! And am listenting to focus@will as I type this, so all is working! Thanks janbar!!!!
