### ISSUE TITLE
Feature request: use scroll wheel do adjust volume

### ISSUE THREAD

**Issue by heis2201** [janbar/noson-app#64]
Hi,
first of all many thanks for this great app!

I would like to suggest the following feature: Being able to use the mouse's scroll wheel to change the volume (on mouse over the volume field).

Cheers!

**Comment by janbar** [comment]
I added the feature by the commit c5415974e6142d0fd689ba76d27c8aa427c283eb

**Comment by janbar** [comment]
The feature is now released with the tag 3.9.4.
Only the seeking slider can't support the wheel actions. For it you could use the keyboard (left , right) to seek back or seek forward.

**Comment by heis2201** [comment]
Feature works great. Thanks again for fast response!
