### ISSUE TITLE
Does not find anything across VLANs

### ISSUE THREAD

**Issue by simonszu** [janbar/noson-app#65]
Hi,

my Sonos Player are located in a different VLAN than my controller (my Android phone). I have enabled an IGMP proxy and specified the appropriate firewall rules. This results in my phone finding and contacting the controllers just fine. 

Noson, sitting in the same subnet as the phone however isn't able to find the players, so i think it could be noson's fault, since other controllers run fine.

**Comment by janbar** [comment]
Probably your firewall is miss configured. Try the following:

    ufw allow out to any
    ufw allow from {IP ADDRESS OF SONOS}

That should work

**Comment by simonszu** [comment]
I use Arch. There is no ufw installed or any iptables rules enabled.

**Comment by janbar** [comment]
Sonos uses SSDP to discover devices. Probably there is something wrong in the firewall rules.
What is the output enabling debug:

    {noson-cmd} --debug

The noson-app command depends of the origin of the package: flathub , snap, ppa

**Comment by simonszu** [comment]
As i have said, i do not have any desktop firewall enabled. The inter-VLAN communication is on "Allow any", with the IGMP proxy enabled. Other controllers (the android app) have no problems finding the players. 

However, this is the result of the debug output:
```
Signal handler is enabled.
"using file ':/i18n/noson_de.qm ' for translations."
installing thumbnails cache in folder "/home/simonszu/.local/share/janbar/noson/QML/OfflineStorage"                   
thumbnailer Last.fm is initialized
qml: LANG=de_DE
thumbnailer: configure key []
(SONOS)ReceiveData: socket(0x7fe7222d6b48) timed out
(SONOS)ReceiveData: socket(0x7fe7222d6b48) timed out
(SONOS)ReceiveData: socket(0x7fe7222d6b48) timed out
(SONOS)ReceiveData: socket(0x7fe7222d6b48) timed out
(SONOS)ReceiveData: socket(0x7fe7222d6b48) timed out
(SONOS)ReceiveData: socket(0x7fe7222d6b48) timed out
(SONOS)ReceiveData: socket(0x7fe7222d6b48) timed out
(SONOS)ReceiveData: socket(0x7fe7222d6b48) timed out
(SONOS)ReceiveData: socket(0x7fe7222d6b48) timed out
(SONOS)ReceiveData: socket(0x7fe7222d6b48) timed out
```

**Comment by simonszu** [comment]
OK, after a little further investigation it turns out i had a misconfigured IGMP proxy. Thanks for your help and your patience, it is working now.
