### ISSUE TITLE
cli fails to find libpulsecommon-11.1.so even if it's there

### ISSUE THREAD

**Issue by Benjalien** [janbar/noson-app#72]
Hi,
I'm trying to run the --cli verson to be able to script the music shutting down when I leave the house. I have an issue on getting it to to run:
noson --cli gives me:
/snap/noson/179/usr/lib/x86_64-linux-gnu/noson/noson-cli: error while loading shared libraries: libpulsecommon-11.1.so: cannot open shared object file: No such file or directory
and locate libpulsecommon-11.1.so gives me:
/snap/noson/179/usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so
so I have it :(

Do you have any clue?
BR
Benjamin

**Comment by janbar** [comment]
Missing a path in the launcher script. I fixed it now. You have to pull the lastest snap release (180).
Thanks for reporting this issue.

**Comment by Benjalien** [comment]
Thanks for fixing the issue :)
