### ISSUE TITLE
openSUSE: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by tr3st0r** [janbar/noson-app#76]
I freshly installed the app from the openSUSE repos and after finding the sonos device it prints 'Segmentation fault (core dumped)' and exits.
Here is the terminal output:
```
ole@W500:~> noson-app
Signal handler is enabled.
"using file ':/i18n/noson_en.qm ' for translations."
installing thumbnails cache in folder "/home/ole/.local/share/janbar/noson/QML/OfflineStorage"
thumbnailer Last.fm is initialized
qml: LANG=en_GB
thumbnailer: configure key []
(SONOS)FindDeviceDescription: starting new context
(SONOS)FindDeviceDescription: location url found (http://192.168.0.101:1400/xml/device_description.xml)
(SONOS)FindDeviceDescription: server string found (Linux UPnP/1.0 Sonos/48.2-61220 (ZPS3))
(SONOS)FindDeviceDescription: search target matches
(SONOS)ParseZoneGroupState: new group 'RINCON_B8E937D0691C01400:1399363919' with coordinator 'RINCON_B8E937D0691C01400'
(SONOS)ParseZoneGroupState: new group member 'RINCON_B8E937D0691C01400' (Portable)
(SONOS)ParseZoneGroupState: topology key 186438505
Segmentation fault (core dumped)
```

**Comment by janbar** [comment]
Thanks to report the issue. I will test it in a virtual host and let you know.

**Comment by janbar** [comment]
First the official version from the opensuse repository is obsolete and probably doesn't work. You have to choose the version 3.11.4 for openSUSE Leap 15.0. Then the provided package is not really usable for a basic user. At first running it doesn't start complaining about missing dependencies. I have to install manually the requirements:

    sudo zypper install libQt5Svg5 libqt5-qtquickcontrols2 libqt5-qtgraphicaleeffects libqt5-qtimageformats

and then it works as expected after disabling the default firewall by the following command:

    sudo systemctl disable firewalld

So at this time you should prefer the package from FLATHUB. You will have the latest release and it is maintained by myself. To install it:

    sudo zypper remove noson-app
    sudo zypper install flatpak
    sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    sudo flatpak install flathub io.github.janbar.noson

Finally close your session and reopen a new to reload KDE/gnome config about flatpak, and search for the application "noson". Also you could run the app from the command line by typing `flatpak run io.github.janbar.noson`.

Obviously **the firewall must be disabled** else you will have to manually configure it.

**Comment by janbar** [comment]
@bosim please could you fix the dependency issue ?

**Comment by tr3st0r** [comment]
Thank you very much, 
I'm sorry I didn't mention that I had installed the libraries you listed and disabled the firewall beforehand. 
With the flatpak it works fine.

**Comment by bosim** [comment]
@tr3st0r If you are interested, you can try the package from multimedia:apps (I update it regularly):
https://software.opensuse.org//download.html?project=multimedia%3Aapps&package=noson-app

I plan to submit most recent version for 15.2

@janbar Sorry for not reacting, I must have overlooked the notification.
