### ISSUE TITLE
Artist artwork issues for those that start with "The"

### ISSUE THREAD

**Issue by jimvlambe** [janbar/noson-app#77]
If an artist's name with "The" i.e. The Beatles, The Smiths, The Strokes it shows in NOSON as Beatles, Smiths and Strokes which seems to be what is passed to Last.fm as the artwork returned is a standard Last.fm "Keep stats clean!" image.

Using v3.11 on Kubuntu 19.04

**Comment by janbar** [comment]
That's weird. Noson doesn"t change artist or title gathered from the Sonos.

**Comment by jimvlambe** [comment]
Yes .... The Controller App is showing "Beatles", "Smiths" and "Strokes" despite all my tags having the correct group names with "The" at the start. So not a problem with Noson. I think I now go and shout at SONOS.
