### ISSUE TITLE
Media scanning does not include Ogg Vorbis files

### ISSUE THREAD

**Issue by sbakker** [janbar/noson-app#82]
When I tell Noson to scan my music library, it finds all MP3 and FLAC files, but completely ignores my (more than 3000) Ogg Vorbis tracks. It seems that Ogg Vorbis support is completely lacking.

Are there any plans on adding this?

**Comment by janbar** [comment]
I never succeeded to stream an ogg file to the Sonos. Although transferring  a flac or mp3 that's work using chunked transfer, oddly that doesn't work with ogg. It requires a more complex method with ogg files. So I kept it back.

**Comment by sbakker** [comment]
Pity. I wish I knew enough about this to hack it myself, but alas.

**Comment by janbar** [comment]
@sandsmark , today I succeeded to stream ogg file to the sonos by handling the http range transfer...
So, soon I will puqh a new release.

**Comment by sbakker** [comment]
This is... amazing! Seriously cool.

**Comment by janbar** [comment]
Hi, can you test the app with the ogg support ?
Also are you able to compile the app from github ?

**Comment by sbakker** [comment]
Just built it on my Fedora box. It picks up many of the OGG/Vorbis files, but not all.
The ones that don't show up result in console output like:
```
parsing /home/<...>/Bluegrass_Vision/15-Friends_in_Raleigh.ogg (OGG) failed
```
These files don't show up in the list at all. Other applications (e.g. Rhythmbox, Totem, VLC) see the files perfectly fine and can play them as well.

Then there are a few files that are parsed OK, but will not play.
Example:
```
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range ()
(SONOS)streamFileByRange: close stream #1 length (81920)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=16511-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=16766-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=17021-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=17276-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=17531-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=17786-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=18041-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=18296-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=18551-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=18806-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=19061-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=19316-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=19571-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=19826-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=20081-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=20336-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=20591-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=20846-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=21101-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=21356-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=21611-)
(SONOS)streamFileByRange: open stream #2 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=21866-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: close stream #2 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=22121-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=22376-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=22631-)
(SONOS)streamFileByRange: close stream #1 length (65536)
(SONOS)streamFileByRange: open stream #1 (/home/sbak319/Music/Beautiful_South,_The/0898/01_-_Old_Red_Eyes_Is_Back.ogg) type (application/ogg) range (bytes=22774-)
(SONOS)streamFileByRange: close stream #1 length (229376)
(SONOS)ParseZoneGroupState: new group 'RINCON_7828CAD013C401400:587947772' with coordinator 'RINCON_7828CAD013C401400'
(SONOS)ParseZoneGroupState: new group member 'RINCON_7828CAD013C401400' (Study)
(SONOS)ParseZoneGroupState: topology key 67244786
```
This is a 160k OGG/Vorbis file. When I click to play it, the above output streams on my console, and I momentarily hear a very short bit of audio (a few tenths of a second). The other tracks on that same album (ripped at the same time with the same settings) do play well.
I've [zipped and attached](https://github.com/janbar/noson-app/files/3612559/broken.zip) a couple of the OGG files:
 * `parse_error-15-Friends_in_Raleigh.ogg` - won't parse, won't show up in the track list.
 * `play_error-12_-_Forgotten_Language.ogg` - shows up in track list, won't play.
 * `play_error-01_-_Old_Red_Eyes_Is_Back.ogg` - shows up in track list, won't play.
 * `play_ok-06_-_36d.ogg` - Shows up in track list, plays ok; from the same album as above.

[broken.zip](https://github.com/janbar/noson-app/files/3612559/broken.zip)

**Comment by janbar** [comment]
I pushed a fix to parse the first track. So now the first track is parsed. But they cannot be played by Sonos. Here only the last play ok as you. I suspect there are some restrictions on the stream type/format to allow the playing by the Sonos device.

- The first track has 2 identification blocks, but in the RFC only 1 is allowed. I fixed the parser to allow more than one. But the sonos device doesn't play it more.

You could try to transcode again those tracks with a recent tool. Maybe it could help. Let me know.

**Comment by janbar** [comment]
Yop, I tried to "repair" the first track using VLC, and now it is playing here. So the stream format was probably broken.

**Comment by janbar** [comment]
Trying to transcode to Flac, then transcode again to Ogg works: the sonos allows to play the new transcoded Ogg.

**Comment by sbakker** [comment]
Thanks, I'll give it a try. The `play_error-12` and `parse_error-15` tracks were ripped by a recent soundjuicer and `play_error-01` and `play_ok-06` came from Grip (yeah, it's ooold).

I'll transcode the lot and report back, though I might also just do OGG->FLAC->MP3; I'll be losing some quality either way, and at least MP3 plays without problems.

**Comment by sbakker** [comment]
It did a transcode from OGG to OGG using `ffmpeg`. This fixed corrupted OGG streams, but still results in parse errors.

I noticed that the files with parse errors have *two* streams inside: the first is a theora stream with what I believe is the cover picture of the album, the second one is the audio:

```
  Duration: 00:05:54.97, start: 0.000000, bitrate: 98 kb/s
    Stream #0:0: Video: theora, yuv420p, 500x492 [SAR 1:1 DAR 125:123], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
      ENCODER         : Lavc58.35.100 libtheora
    Stream #0:1: Audio: vorbis, 44100 Hz, stereo, fltp, 112 kb/s
    Metadata:
      ALBUM           : Henry's Dream
      DISCTOTAL       : 01
      ARTIST          : Nick Cave & The Bad Seeds
      TITLE           : Papa Won't Leave You, Henry
      TRACKTOTAL      : 09
      DATE            : 1992
      album_artist    : Nick Cave & The Bad Seeds
      COMPOSER        : Nick Cave
      GENRE           : Rock
      track           : 01
      disc            : 01
      ENCODER         : Lavc58.35.100 libvorbis
```
This is allowed by the OGG container specification AFAIK, and players like VLC, rhythmbox and totem know which streams to select, but it would seem your parser expects a single (Vorbis) stream only (if I read the code correctly). In fact, I have OGG files where the video stream is the second one (so the audio stream is the first), and this causes no problems for noson.

I guess I can get around this by adding `-map 0:a` to `ffmpeg` to remove the theora stream, but ideally the parser should be able to pick out the audio stream only.

**Comment by janbar** [comment]
Can you send me this one for testing. Thanks.

**Comment by sbakker** [comment]
Ouch. I'm afraid I already stripped the video stream from the track. :-(

However, I'll do you one better! I have a few other tracks with a video stream, except that the video stream comes *after* the audio stream. The noson-app reads those just fine. So, with a little `ffmpeg` magic I reordered them and, presto, the app reports a parse error.

In the [attached zip file](https://github.com/janbar/noson-app/files/3614066/ogg-with-video-stream.zip), `Breeders_Canonball-audio-vid.ogg` should parse/play fine, `Breeders_Canonball-vid-audio.ogg` is likely to fail.

[ogg-with-video-stream.zip](https://github.com/janbar/noson-app/files/3614066/ogg-with-video-stream.zip)

**Comment by janbar** [comment]
Yop, I tested the ogg files, and improved the ogg parser. Unfortunately the Sonos device doesn't support ogg files with a video stream as main stream (the first):

`TransportStatus = ERROR_UNSUPPORTED_FORMAT`

The ogg file with an audio stream as main stream is playable with the Sonos. I hope you haven't so much file with a video stream as main stream...

**Comment by sbakker** [comment]
Thanks for verifying. I don't have that many files with a video stream as the first item, and the ones I had I already re-ordered, so as far as I am concerned, the issue is fixed.

I'm guessing the Sonos also looks at the first stream and determines the media type based on that. If it's a Vorbis stream, it's audio. If it's a Theora stream, it's unsupported. It took me a while to understand that OGG is not an audio format, it's a container (like MKV, AVI, MP4).

This also explains why e.g. my Plex and Synology refused to play certain OGG files: some files were corrupted, others had the wrong stream order.

I'm still not sure which program was responsible for doing this. Suspects are Easytag, Picard, or Tagtool.

This has been very illuminating. :-)

**Comment by sbakker** [comment]
Shall I close the issue?

**Comment by janbar** [comment]
Yep all could be done has been done
