### ISSUE TITLE
stuttering playback after days of normal use

### ISSUE THREAD

**Issue by leder11011** [janbar/noson-app#85]
I installed noson-app on ubuntu as described on github. Everything is fine until after some days of use, the playback is not working well: I experienced stuttering and once my whole system froze.

Hope to be of help
Gerrit

**Comment by janbar** [comment]
Which system froze ?   The Sonos device or Ubuntu ?
That's related to the stream source and the network throughput.
If you are using noson-app to stream your local music (in ubuntu), you have to check the network throughput between the host and the Sonos device.

**Comment by leder11011** [comment]
The Ubuntu system was not reacting : the mouse was moving though. Could it
be some memory leak?

How do I measure network throughput? I am streaming amazon music.

Gerrit

Jean-Luc Barrière <notifications@github.com> schrieb am Sa., 14. Sep. 2019,
13:31:

**Comment by janbar** [comment]
Streaming amazon music is done by the Sonos device itself. The app is only a controler while you don't stream your local music files or pulse-audio. You can see what causing the trouble with the system monitor.

**Comment by leder11011** [comment]
when I connect noson to symfonisk via amazon music and leave it running untouched for some hours, even without playback: then playback via noson or sonos android app breaks! Android app says "no connection to amazon music".

After killing noson and sonos android app: sonos android app playback is working fine, without noson running.

Hope to be of help
Gerrit

**Comment by janbar** [comment]
I think the cause is the Internet bandwidth. The controllers Sonos even Noson get cover images from the providers. When the bandwidth is too fine you will have stuttering playing a stream from internet.

**Comment by leder11011** [comment]
Hello Jean-Luc,

no, I do not think so. Every app is doing fine: Windows, Android are playing for hours. Only noson I experience a broken control of amazon music streaming. And I really would like to  use my Ubuntu PC: can you do anything for it?

Cheers
Gerrit

P. S. my LAN speed down/up is 42/12 Mbit/s and 9 ping being online.

**Comment by janbar** [comment]
Mmm, my WAN(intenet) has 14down/1up Mbits/s and my LAN around same of you. I tested playing a Deezer playlist, and browsing the Amazon service sample (lot of track/album). All cover arts download fast, the the browsing of amazon catalog is smooth and I haven't any stuttering of the playback from Deezer. Bizarre. I am using Ubuntu 18.04.3 LTS. I provide the app for Android, MAC and Windows64 too and all is smooth with my Android phone, the same with my Mac and the same with Windows10.
I don't think the cause is tour LAN, but it could be your WAN instead. The Sonos device streams from Amazon and the app download covers from Amazon too, or from others providers. It depends what you are currently browsing.

**Comment by leder11011** [comment]
One thing could be my power plan : I do not have WiFi on my pc, so I
connect to the WAN by power cord adapter. But it is usually enough for
streaming locally 1080p and you see my 42 MBit / sec download from the
Internet : so WAN is OK, too. My android and Windows app use the same WAN
with WiFi and have full 51 MBit / sec down and 12 MBit / sec up when online.

I have no clue what else could be the issue! Have you streamed amazon for
4-5h?

Gerrit

Jean-Luc Barrière <notifications@github.com> schrieb am Sa., 21. Sep. 2019,
20:52:

**Comment by janbar** [comment]
You could get logs when it occurs:

noson-app --debug 2>&1 | tee noson.log

Then we will see if there is a call could cause the issue.

**Comment by leder11011** [comment]
I have same error now after four hours of streaming with noson-app from amazon music: noson.log  send to your email!

**Comment by janbar** [comment]
I released the version 4.0 now. Maybe it could help to resolve your issue. In your log I didn't see any errors or calls could cause the issue. You could be lucky with the new release.
