### ISSUE TITLE
Spotify Not Viewable

### ISSUE THREAD

**Issue by voice06** [janbar/noson-app#86]
Not sure if something changed on Spotify's end but selecting it in the My Services option results in a blank page and range=en_us. The official Sonos app is still able to browse Spotify and presently Noson is able to control it after a selection has been initially made via the Sonos apps.

A little more detail, running noson v3.13.1 / libnoson 1.13.2, pulled from the PPA.

Yet even more details, this is what the console shows:
(SONOS)SSLSessionFactory: SSL engine initialized
(SONOS)WSResponse: server error (500)
(SONOS)WSResponse: server error (500)
qml: Fault: range=en_us

**Comment by janbar** [comment]
They have probably changed something, and seems now they check the range of language. I was lazy about this thing and I pushed a commit to fix it in the release 3.14.2. It is available from the PPA.

**Comment by janbar** [comment]
Please let me know if that fix the issue.

**Comment by voice06** [comment]
Can confirm that it is now fixed, thanks.
