### ISSUE TITLE
Search results broken

### ISSUE THREAD

**Issue by DasJott** [janbar/noson-app#88]
This is the answer to all search results currently:
![image](https://user-images.githubusercontent.com/6298761/65304452-f12bff00-db80-11e9-8c7c-465530d88c2b.png)

Linux Arch

**Comment by janbar** [comment]
Does occur in the Spotify service ?

**Comment by janbar** [comment]
It should be fixed since the release 3.14.3 (libnoson 1.14.2) is out. What is the release of the app ?

**Comment by DasJott** [comment]
Yes, it occurs in Spotify service. 

The version of the app is:
3.13.1 (libnoson 1.13.2

Thank you! :)

**Comment by DasJott** [comment]
This one seems to be fixed now.
