### ISSUE TITLE
MP3: numeric genre in TCON field in ID3v2 is not parsed properly

### ISSUE THREAD

**Issue by sbakker** [janbar/noson-app#89]
ID3v1 has a genre field that is numerical. It seems that `noson-app` can parse and translate that fine, e.g. the number `132` is translated to `BritPop`. But if the file contains an ID3v2 header with a TCON field of `(132)`, it will not do this translation.

The ID3v2 specification says that TCON is a text field, but it may contain references to the ID3v1 numerical list, by having the number in parenthesis, see http://id3.org/id3v2.3.0#TCON

As an example, I attached [a zip file with three MP3 tracks](https://github.com/janbar/noson-app/files/3636616/test-id3.zip):

 * `test-v1` contains only ID3v1 metadata
 * `test-v2` contains only ID3v2 metadata
 * `test-v1v2` contains both ID3v1 and ID3v2 metadata

It seems that the ID3v2 information is preferred over ID3v1, but the numerical genre reference is not handled well.

Ref: [test-id3.zip](https://github.com/janbar/noson-app/files/3636616/test-id3.zip)

**Comment by janbar** [comment]
HI, it should be fixed with the commit aee6c2ca7ea00906ac9c2ed67e3b5a838254f395.
Please let me know.

**Comment by sbakker** [comment]
Is there any way to test media scanning without connecting to a Sonos zone? (Currently oud of the home.)

**Comment by janbar** [comment]
Yes. Here I join the sources to run  a demo showing the basic list of genre.
[mediascanner.zip](https://github.com/janbar/noson-app/files/3648818/mediascanner.zip)

**Comment by sbakker** [comment]
Hi, just tried again with the latest commit. There were still a couple of tracks that showed up weird, but that was probably due to corrupted/conflicting ID3v1/v2 tags, because my e.g. Rhythmbox and others showed weird results as well (mostly "Unknown" or "Undefined"). Easy fix with puddletag.

**Comment by sbakker** [comment]
For me it looks good now, thanks!
