### ISSUE TITLE
Pocket Casts lost authorisation after restart

### ISSUE THREAD

**Issue by Hellmudth** [janbar/noson-app#91]
Adding Pocket Casts as an service can complete, all subscptions are shown, but after restart of noson-app you have to re run the registrate to the service.
I am on Linux: 
Noson Version: 3.15.1 (libnoson 1.6.1)
Operating System: KDE neon Testing Edition
KDE Plasma Version: 5.16.90
KDE Frameworks Version: 5.63.0
Qt Version: 5.13.1
Kernel Version: 4.15.0-65-generic
OS Type: 64-bit

**Comment by janbar** [comment]
The bug is caused because this service doesn't support the token refreshing. I fixed it in the new release 3.15.2. Let me know once the release will be available.

**Comment by Hellmudth** [comment]
Hi Janbar, just got the update and works!
Thank you for fast Solution. Great job.
