### ISSUE TITLE
Feature request: MPRIS support

### ISSUE THREAD

**Issue by callebjorkell** [janbar/noson-app#92]
Implementing MPRIS (https://specifications.freedesktop.org/mpris-spec/latest/) would allow remotes to easily control the application, and allow another usage of tools like playerctl (https://github.com/altdesktop/playerctl) to build on, or even replace, the scriptability that the CLI mode allows for currently. It would be awesome to see this for anyone on a system using dbus.

**Comment by janbar** [comment]
I implemented basic functions with MPRIS now. Need to run some tests and cleanup. Currently it needs to launch the app (not the cli).

**Comment by callebjorkell** [comment]
Awesome! What can I do to help test that out?

**Comment by janbar** [comment]
It is building at launchpad for the ubuntu packages ...
Also you could build from sources from the master branch. I had to change the app id (noson) to the official name (io.github.janbar.noson), so I included the setting migration in the startup shell noson-app. The startup script will rename the old settings with the new name and let you keep the service settings etc. If you test the app by the command 'make run' , that doesn't run this script.
