### ISSUE TITLE
Search Dialog - Filter type selection empty

### ISSUE THREAD

**Issue by DasJott** [janbar/noson-app#93]
If you want to search within Spotify, you once could select to chose by artist, station or whatever...
Now that selectbox is empty.

Newest Version  running on LInux Arch

**Comment by janbar** [comment]
Could you send to my email jlbarriere68@gmail.com , the debug log by running the app as the following:

noson-app --debug 2>&1 | tee noson.log

**Comment by MayorOfAlbuquerque** [comment]
I am also having this issue on Mint. Looks like this
![Screenshot from 2019-10-31 10-19-10](https://user-images.githubusercontent.com/16918778/67938710-ede85200-fbc7-11e9-8ef0-1e954c2b6a8e.png)

**Comment by DasJott** [comment]
Will send you logs in a bit.

**Comment by janbar** [comment]
Thanks. I am working on and I found the issue. It seems Spotify has updated its services description and now it doesn't provide any more a presentation map for search categories. Then it seems the sonos app default them with basic categories: artist, album, track and playlist. I will make an update soon to work as the same way.

**Comment by DasJott** [comment]
Thank you very much for your work, man!

Am Mi., 6. Nov. 2019 um 22:35 Uhr schrieb Jean-Luc Barrière <
notifications@github.com>:

**Comment by janbar** [comment]
Fixed
